Repository PlutosCapstone/Plutos, pull requests merged in 2024-10, with the labels that each got.

#16 chore: initialize project repo for development
  src/Plutos/.gitignore
  src/Plutos/App.js
  src/Plutos/app.json
  src/Plutos/assets/adaptive-icon.png
  src/Plutos/assets/favicon.png
  src/Plutos/assets/icon.png
  src/Plutos/assets/splash.png
  src/Plutos/babel.config.js
  src/Plutos/package-lock.json
  src/Plutos/package.json
  src/README.md
Labels: chore

#18 chore: add in certain sections to SRS doc
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#19 chore: update SRS with subsections 2/3
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#21 chore: update SRS doc
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: chore

#22 Update SRS with more section details
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
  docs/SRS/SystemContext.png
Labels: documentation, chore

#26 appendix reflection for srs doc
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#46 docs: add initial draft to hazards doc
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#48 docs: hazard analysis add sec 6 and 7
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation
