Repository PlutosCapstone/Plutos, pull requests merged in 2025-01, with the labels that each got.

#134 feat: firebase config and authentication setup
  src/client/components/view/LoginView.js
  src/client/firebase.ts
  src/client/package-lock.json
  src/client/package.json
  src/client/styles/commonStyles.js
Labels: feature

#133 docs: add some details to timeline on MG
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#131 uses hierarchy diag
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftArchitecture/UsesHierarchy.png
Labels: documentation

#129 docs: fill in basics of MIS sections 2-5
  .github/workflows/compile-tex.yml
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/ProblemStatementAndGoals/ProblemStatement.pdf
  docs/SRS/SRS.pdf
  docs/UserGuide/UserGuide.pdf
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVReport/VnVReport.pdf
Labels: documentation

#136 reflection for MIS
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/ProblemStatementAndGoals/ProblemStatement.pdf
  docs/SRS/SRS.pdf
  docs/UserGuide/UserGuide.pdf
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVReport/VnVReport.pdf
Labels: documentation

#140 feat: add in register page
  src/client/App.js
  src/client/components/view/LoginView.js
  src/client/components/view/RegisterView.js
Labels: feature

#142 expo upgrade to allow app to be used on phone
  src/client/components/view/AddExpenseView.js
  src/client/package-lock.json
  src/client/package.json
  src/client/tsconfig.json
Labels: chore

#141 chore: ts project setup
  src/client/api/api.ts
  src/client/components/common/EntrySource.tsx
  src/client/components/common/HomePageButton.tsx
  src/client/components/common/HorizontalRule.tsx
  src/client/components/view/AddCategoryBudgetModal.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/AddExpenseView.tsx
  src/client/components/view/DisplayExpenseItem.tsx
  src/client/components/view/LoginView.tsx
  src/client/components/view/MyBudget.tsx
  src/client/components/view/MyExpenses.tsx
  src/client/components/view/MyIncome.tsx
  src/client/components/view/NewBudgetPage.tsx
  src/client/components/view/NewIncomePage.tsx
  src/client/components/view/OverView.tsx
  src/client/package-lock.json
  src/client/package.json
  src/client/styles/commonStyles.ts
  src/client/tsconfig.json
Labels: chore

#144 feat: add in user sign in authentication
  src/client/components/view/RegisterView.tsx
Labels: feature

#145 feat: reset password page + send email for resetting password
  src/client/App.js
  src/client/components/view/LoginView.tsx
  src/client/components/view/ResetPasswordView.tsx
Labels: feature

#165 feat: add in onboarding page
  src/client/App.js
  src/client/assets/icons/CheckMark.js
  src/client/components/view/OnboardingView.tsx
  src/client/components/view/RegisterView.tsx
  src/client/package-lock.json
  src/client/package.json
Labels: feature

#168 feat: update firebase to use async storage for authentication
  src/client/firebase.ts
  src/client/package-lock.json
  src/client/package.json
  src/client/tsconfig.json
Labels: feature

#170 chore: typescript error fixes
  src/client/App.tsx
  src/client/assets/icons/AddCircleIcon.js
  src/client/assets/icons/AddIcon.js
  src/client/assets/icons/AppleIcon.js
  src/client/assets/icons/BackArrow.js
  src/client/assets/icons/BudgetIcon.js
  src/client/assets/icons/CameraIcon.js
  src/client/assets/icons/CheckMark.js
  src/client/assets/icons/GoogleIcon.js
  src/client/assets/icons/GroupIcon.js
  src/client/assets/icons/IncomeIcon.js
  src/client/assets/icons/MicrosoftIcon.js
  src/client/assets/icons/PeopleIcon.js
  src/client/assets/icons/PersonIcon.js
  src/client/assets/icons/PhotoLibraryIcon.js
  src/client/assets/icons/ReceiptIcon.js
  src/client/assets/icons/RightArrow.js
  src/client/assets/icons/StatsChartOutlineIcon.js
  src/client/components/common/EntrySource.tsx
  src/client/components/common/HomePageButton.tsx
  src/client/components/view/AddCategoryBudgetModal.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/AddExpenseView.tsx
  src/client/components/view/DisplayExpenseItem.tsx
  src/client/components/view/LoginView.tsx
  src/client/components/view/MyBudget.tsx
  src/client/components/view/MyExpenses.tsx
  src/client/components/view/MyIncome.tsx
  src/client/components/view/NewBudgetPage.tsx
  src/client/components/view/NewIncomePage.tsx
  src/client/components/view/OnboardingView.tsx
  src/client/components/view/OverView.tsx
  src/client/components/view/RegisterView.tsx
  src/client/components/view/ResetPasswordView.tsx
  src/client/types.ts
Labels: chore

#171 feat: onboarding view UI fixes
  src/client/components/view/OnboardingView.tsx
  src/client/firebase.ts
  src/client/package-lock.json
  src/client/package.json
Labels: feature

#201 chore: supabase setup for postgresql
  src/client/components/view/LoginView.tsx
  src/client/package-lock.json
  src/client/package.json
  src/client/supabase.ts
Labels: chore
