Repository PlutosCapstone/Plutos, pull requests merged in 2025-02, with the labels that each got.

#205 feat: add in income update/delete endpoints to backend
  src/server/__init__.py
  src/server/controllers/incomes/incomes_controller.py
  src/server/daos/incomes/incomes_dao.py
  src/server/routes/incomes/incomesRoutes.py
Labels: backend (apis)

#206 feat: set up supabase in backend and call endpoints
  src/client/api/api.ts
  src/client/components/view/LoginView.tsx
  src/client/services/incomeService.js
  src/server/app.py
  src/server/controllers/incomes/incomes_controller.py
  src/server/daos/incomes/incomes_dao.py
  src/server/db.py
  src/server/models/incomes/income.py
  src/server/requirements.txt
  src/server/routes/incomes/incomesRoutes.py
Labels: backend (apis)

#211 feat: (backend) CRUD operations for managing users
  src/client/services/managerUserService.js
  src/server/__init__.py
  src/server/controllers/__init__.py
  src/server/controllers/users/__init__.py
  src/server/controllers/users/users_controller.py
  src/server/daos/__init__.py
  src/server/daos/users/__init__.py
  src/server/daos/users/users_dao.py
  src/server/models/__init__.py
  src/server/models/users/__init__.py
  src/server/models/users/user.py
  src/server/routes/__init__.py
  src/server/routes/users/__init__.py
  src/server/routes/users/usersRoutes.py
Labels: backend (apis)

#217 feat: frontend register user page to records data into db
  src/client/App.tsx
  src/client/components/view/OnboardingView.tsx
  src/client/components/view/RegisterView.tsx
  src/client/components/view/ResetPasswordView.tsx
  src/client/services/managerUserService.js
Labels: frontend

#219 feat: create profile page and and clean up
  src/client/App.tsx
  src/client/components/view/DeleteProfileModal.tsx
  src/client/components/view/HomePage.tsx
  src/client/components/view/LoginView.tsx
  src/client/components/view/OnboardingView.tsx
  src/client/components/view/ProfilePage.tsx
  src/client/components/view/RegisterView.tsx
  src/client/contexts/UserContext.tsx
  src/client/utils.ts
Labels: frontend

#222 bug with expense modal and add expense/bulk add expense
  src/client/components/common/ExpensesList.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/AddExpenseView.tsx
  src/client/components/view/DisplayExpenseItem.tsx
  src/client/services/expensesService.js
  src/server/controllers/expenses/expenses_controller.py
  src/server/daos/expenses/expenses_dao.py
  src/server/imageProcessing/process.py
  src/server/models/expenses/expense.py
  src/server/routes/expenses/expensesRoutes.py
Labels: bug, feature, frontend, backend (apis)
