Repository PlutosCapstone/Plutos, pull requests merged in 2025-03, with the labels that each got.

#242 combining budget with income
  src/client/App.tsx
  src/client/assets/icons/BudgetIcon.js
  src/client/assets/icons/CancelIcon.js
  src/client/assets/icons/CartIcon.js
  src/client/assets/icons/CoinIcon.js
  src/client/assets/icons/ComputerIcon.js
  src/client/assets/icons/HouseIcon.js
  src/client/assets/icons/LaundryIcon.js
  src/client/assets/icons/MoviesIcon.js
  src/client/assets/icons/ReceiptIcon.js
  src/client/assets/icons/WifiIcon.js
  src/client/components/common/BudgetBox.tsx
  src/client/components/common/EntrySource.tsx
  src/client/components/common/HomePageButton.tsx
  src/client/components/common/HomePageMetricsBox.tsx
  src/client/components/common/IncomeBox.tsx
  src/client/components/common/MyBudgetsBox.tsx
  src/client/components/common/NewBudgetModal.tsx
  src/client/components/common/NewIncomeModal.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/HomePage.tsx
  src/client/components/view/LoginView.tsx
  src/client/components/view/ManagePage.tsx
  src/client/components/view/MyBudget.tsx
  src/client/components/view/MyIncome.tsx
  src/client/components/view/NewIncomePage.tsx
  src/client/constants.js
  src/client/constants.ts
  src/client/package-lock.json
  src/client/services/budgetService.js
  src/client/services/expensesService.js
  src/client/types.ts
  src/client/utils/util.ts
  src/server/__init__.py
  src/server/controllers/budget/__init__.py
  src/server/controllers/budget/budget_controller.py
  src/server/controllers/expenses/expenses_controller.py
  src/server/daos/budget/__init__.py
  src/server/daos/budget/budget_dao.py
  src/server/daos/expenses/expenses_dao.py
  src/server/daos/incomes/incomes_dao.py
  src/server/models/budget/__init__.py
  src/server/models/budget/budget.py
  src/server/routes/budget/__init__.py
  src/server/routes/budget/budgetRoutes.py
  src/server/routes/expenses/expensesRoutes.py
Labels: feature

#243 chore: add unit testing framework
  src/client/components/common/NewIncomeModal.tsx
  src/client/components/view/HomePage.tsx
  src/client/components/view/ProfilePage.tsx
  src/client/package-lock.json
  src/client/package.json
  src/client/tests/EntrySource.test.tsx
  src/client/tests/NewIncomeModal.test.tsx
  src/client/tests/UtilityFunctions.test.tsx
  src/client/tests/__snapshots__/EntrySource.test.tsx.snap
  src/client/tests/__snapshots__/NewIncomePage.test.tsx.snap
  src/client/utils.ts
  src/client/utils/util.ts
Labels: chore

#246 test: remaining api tests
  src/server/tests/budget/__init__.py
  src/server/tests/budget/test_budget.py
  src/server/tests/expense/__init__.py
  src/server/tests/expense/test_expense.py
  src/server/tests/users/__init__.py
  src/server/tests/users/test_users.py
Labels: backend (apis)

#244 budget and expense metrics
  src/client/App.tsx
  src/client/components/common/BudgetBox.tsx
  src/client/components/common/BudgetBoxDetails.tsx
  src/client/components/common/HomePageMetricsBox.tsx
  src/client/components/common/IncomeBox.tsx
  src/client/components/common/MyBudgetsBox.tsx
  src/client/components/common/NewBudgetModal.tsx
  src/client/components/common/NewIncomeModal.tsx
  src/client/components/common/SpendingDetails.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/AddExpenseView.tsx
  src/client/components/view/HomePage.tsx
  src/client/components/view/MyBudget.tsx
  src/client/components/view/MyExpenses.tsx
  src/client/components/view/NewBudgetPage.tsx
  src/client/constants.ts
  src/client/types.ts
  src/client/utils/util.ts
Labels: feature

#252 unit testing section in vnv report
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#289 feat: add autocompletion to expense/store titles
  src/client/components/common/HomePageMetricsBox.tsx
  src/client/components/view/AddExpenseModal.tsx
  src/client/components/view/AddExpenseView.tsx
  src/client/components/view/LoginView.tsx
  src/client/components/view/MyExpenses.tsx
  src/client/services/expensesService.js
  src/server/controllers/transactions/transactions_controller.py
  src/server/daos/expenses/expenses_dao.py
  src/server/daos/transactions/transactions_dao.py
  src/server/routes/transactions/transactionsRoutes.py
Labels: frontend
